WIP: Implemented Labeled and Unlabeled Radio Button Components
Lern-PFR/lern-web pull request #22
Opened 2021-04-30 12:55 UTC by frenchykiller

2021-04-30 13:50 UTC, frenchykiller commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to have an reusable radio button component.](https://trello.com/c/uGyQo0xO/26-as-a-developer-i-want-to-have-an-reusable-radio-button-component)

2021-05-04 13:09 UTC, yannhodiesne commented on src/components/shared/form/RadioButtonComponent.jsx
> +				defaultChecked={checked}
Séparer `defaultChecked` et `checked` est préférable
Dans le cas où ce composant serait utilisé avec un state qui tente de le contrôler intégralement, defaultChecked ne mettra pas à jour la valeur du RadioButton à la mise à jour du state

2021-05-04 13:09 UTC, yannhodiesne commented on src/components/shared/form/RadioButtonComponent.jsx
> +				defaultChecked={checked}
à vérifier aussi côté Checkbox

2021-05-04 13:10 UTC, yannhodiesne commented on tests/components/shared/form/LabeledRadioButton.test.js
> +describe('LabeledRadioButton', () => {
Les noms de tests parlent encore d'un composant de `checkbox`

2021-05-04 13:11 UTC, yannhodiesne commented on tests/components/shared/form/RadioButtonComponent.test.js
> +	it('should not call the onChange method when checkbox is disabled', async () => {
idem: `checkbox`

2021-05-04 13:12 UTC, yannhodiesne requested changes
Des changements sont à faire avant l'approbation

2021-05-11 14:28 UTC, simonfranza commented on src/components/shared/form/LabelComponent.jsx
> +	<Brevier tag="label" {...otherProps} {...labelStyle} htmlFor={forId}>
le otherProps doit toujours rester en dernier pour permettre d'override certaines propriétés css si besoin.

2021-05-11 14:29 UTC, once-upon-a-tam commented on src/components/shared/form/LabeledRadioButton.jsx
> +				<RadioButtonComponent {...otherProps} name={name} disabled={disabled} checked={checked} id={id} ref={resolvedRef} />
Mets le otherProps en dernier (juste une question de clean code)

2021-05-11 14:31 UTC, simonfranza commented on src/theme/formStyles.js
> +		content: '',
à vérifier mais il me semble qu'il faut mettre une valeur du style '""' pour que tous les navigateurs soient ok

2021-05-11 14:33 UTC, once-upon-a-tam commented on src/theme/formStyles.js
> +		content: '',
à vérifier mais il me semble qu'il faut mettre une valeur du style `'""'` (2 double quotes entre 2 simple quotes) pour que tous les navigateurs soient ok.
Certains considèrent que `''` (deux simple quotes) est une valeur incorrecte pour l'attribut `content.

2021-05-11 14:35 UTC, simonfranza commented on tests/components/shared/form/LabeledRadioButton.test.js
> +		const sut = (<LabeledRadioButton id="lcb" name="rg">Primary button</LabeledRadioButton>);
Bizarre d'utiliser "Primary Button" comme label d'une checkbox, non ? x)

2021-05-11 14:35 UTC, once-upon-a-tam commented on tests/components/shared/form/LabeledRadioButton.test.js
> +		const sut = (<LabeledRadioButton disabled checked id="lcb" name="rg">Primary button</LabeledRadioButton>);
Je me demande si ça passe pour la récupération des données un `checked disabled`, ou s'il vaut mieux pas utiliser `readonly` plutôt.

2021-05-11 14:37 UTC, once-upon-a-tam commented on tests/components/shared/form/RadioButtonComponent.test.js
> +	it('should call the onChange method', async () => {
Spécifie l'action qui entraine l'appel

2021-05-11 14:40 UTC, simonfranza requested changes
Quelques modifications à apporter pour améliorer la qualité du code

2021-05-11 17:22 UTC, frenchykiller commented on tests/components/shared/form/LabeledRadioButton.test.js
> +		const sut = (<LabeledRadioButton disabled checked id="lcb" name="rg">Primary button</LabeledRadioButton>);
S'il est disabled on s'en fou de récupérer les données dedans puisqu'elles ne doivent pas changer.
Exemple:
J'ai une checkbox qui passe en disabled suite à un choix sur le formulaire. Si la personne coche la case puis fait la modification qui entraine la désactivation de la checkbox, je ne veux pas que l'état "checked" soit transmis au submit du form. Si je mets un readonly ça n'a plus de sens. Si, avant de soumettre le formulaire, la personne enlève ladite modification, la checkbox repasse en enabled et sa valeur checked est prise en compte (sans nécessiter que la personne coche à nouveau cette case)

2021-05-11 17:46 UTC, frenchykiller commented on src/components/shared/form/RadioButtonComponent.jsx
> +				defaultChecked={checked}
D'après la [doc react](https://reactjs.org/docs/uncontrolled-components.html) et [ce issue](https://github.com/facebook/react/issues/13167) il faut choisir entre `defaultChecked` et `checked`. Le problème avec `checked` étant qu'on ne peut avoir de valeur initiale sur un composant non-controllé, c'[ est pour ça que le `defaultChecked` existe (la même chose est applicable aux checkbox).

2021-05-11 17:49 UTC, frenchykiller commented on tests/components/shared/form/RadioButtonComponent.test.js
> +	it('should not call the onChange method when checkbox is disabled', async () => {
corrigé

2021-05-11 17:50 UTC, frenchykiller commented on src/components/shared/form/LabelComponent.jsx
> +	<Brevier tag="label" {...otherProps} {...labelStyle} htmlFor={forId}>
corrigé

2021-05-11 17:53 UTC, frenchykiller commented on src/theme/formStyles.js
> +		content: '',
Testé et fonctionnel sous Chrome, Firefox et Edge, mais je l'ai changé pour éviter des soucis éventuels sous d'autres navigateurs.

2021-05-11 17:55 UTC, frenchykiller commented on src/theme/formStyles.js
> +		content: '',
Testé et fonctionnel sous Chrome, Firefox et Edge, mais changé pour éviter d'eventuels soucis dans d'autres navigateurs

2021-05-11 17:55 UTC, frenchykiller commented on tests/components/shared/form/LabeledRadioButton.test.js
> +		const sut = (<LabeledRadioButton id="lcb" name="rg">Primary button</LabeledRadioButton>);
corrigé

2021-05-11 17:55 UTC, frenchykiller commented on src/components/shared/form/LabeledRadioButton.jsx
> +				<RadioButtonComponent {...otherProps} name={name} disabled={disabled} checked={checked} id={id} ref={resolvedRef} />
corrigé

2021-05-11 18:01 UTC, frenchykiller commented on tests/components/shared/form/RadioButtonComponent.test.js
> +	it('should call the onChange method', async () => {
corrigé

2021-05-11 20:59 UTC, once-upon-a-tam approved these changes

2021-05-14 15:32 UTC, yannhodiesne commented on src/components/shared/form/RadioButtonComponent.jsx
> +				defaultChecked={checked}
Ok, autant laisser tel quel et laisser à l'utilisateur du composant le choix d'ajouter une prop `value` s'il veut le contrôler, vu que `value` prendra le dessus sur `defaultValue`

2021-05-14 15:45 UTC, merged