Implemented the module details page
Lern-PFR/lern-web pull request #23
Opened 2021-04-30 13:45 UTC by simonfranza

Its data is mocked for the moment, as we don't have a way to create nor retrieve subjects and modules.
You can test this PR by clicking on one of the modules from the `/subjects/1` url.

2021-04-30 13:45 UTC, simonfranza commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to have the shell for the module's notions list page.](https://trello.com/c/LWUJ8BRp/38-as-a-developer-i-want-to-have-the-shell-for-the-modules-notions-list-page)

2021-05-03 15:55 UTC, frenchykiller requested changes

2021-05-03 15:55 UTC, frenchykiller commented on src/i18n/en.json
> +				"access": "Access lesson"
"Go to lesson" or "View lesson" sounds better here

2021-05-03 15:55 UTC, frenchykiller commented on src/i18n/en.json
> +				"back_to_subject": "Get back to subject's page"
"Return to subject main page"

2021-05-11 18:05 UTC, frenchykiller approved these changes

2021-05-11 21:00 UTC, merged