Implemented the notion details page
Lern-PFR/lern-web pull request #26
Opened 2021-05-22 17:16 UTC by simonfranza

Its data is mocked for the moment, as we don't have a way to create nor retrieve real data.
You can test this PR using the `/notions/1` url.

2021-05-22 17:16 UTC, simonfranza commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to have the shell of a notion's details page.](https://trello.com/c/aJmnkji3/48-as-a-developer-i-want-to-have-the-shell-of-a-notions-details-page)

2021-05-26 10:23 UTC, frenchykiller requested changes

2021-05-26 10:23 UTC, frenchykiller commented on src/components/App.jsx
> +			<LabeledCheckbox id="lcb1">Labeled checkbox</LabeledCheckbox>
l.81 à l.86 obsolètes

2021-05-26 10:23 UTC, frenchykiller commented on src/components/App.jsx
> +			<FieldsetComponent title="Basic fieldset component" display="flex" flexDirection="column" gridGap=".5em">
`title` devrait être "Basic checkbox component"

2021-05-26 10:23 UTC, frenchykiller commented on src/components/App.jsx
> +		<StyledDiv position="relative" display="flex" flexDirection="column" gridGap=".5em">
l.95 à l.99 obsolètes

2021-05-26 10:23 UTC, frenchykiller commented on src/components/App.jsx
> +			<FieldsetComponent title="Basic fieldset component" display="flex" flexDirection="column" gridGap=".5em">
`title` devrait être "Basic radio button components"

2021-05-26 10:23 UTC, frenchykiller commented on src/theme/formStyles.js
> +		backgroundColor: parsnip.lighter1,
attention au hover d'un radio button disabled

2021-05-26 10:23 UTC, frenchykiller commented on tests/components/notions/QuestionForm.test.js
> +			fireEvent.click(screen.getAllByRole('radio')[0]);
utiliser userEvent.click au lieu de fireEvent.click

2021-05-26 15:15 UTC, frenchykiller approved these changes

2021-05-26 15:16 UTC, merged