Implemented the Navbar component and set the mainLayout as the parent of all pages.
Lern-PFR/lern-web pull request #29
Opened 2021-05-25 21:17 UTC by simonfranza

2021-05-25 21:24 UTC, simonfranza commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want to have a navbar.](https://trello.com/c/E70As8rQ/50-as-a-user-i-want-to-have-a-navbar)

2021-05-26 07:24 UTC, yannhodiesne commented on src/components/shared/navigation/navbar/NavbarLink.jsx
> +);
The navigation occurs only when clicking the text inside `StyledNavLink`
We should relocate the padding of the container to avoid this

2021-05-26 07:31 UTC, yannhodiesne commented on src/components/shared/navigation/navbar/NavbarLink.jsx
> +);
Oops, `PrimaryButton` is the component affected by this bug, not this one

2021-05-26 08:35 UTC, frenchykiller requested changes

2021-05-26 08:35 UTC, frenchykiller commented on tests/components/shared/navigation/navbar/Navbar.test.js
> +	it('should match previous snapshot with no authentified user', () => {
authenticated

2021-05-26 08:35 UTC, frenchykiller commented on tests/components/shared/navigation/navbar/Navbar.test.js
> +	it('should match previous snapshot with an authentified user', () => {
authenticated

2021-05-26 08:37 UTC, yannhodiesne approved these changes

2021-05-26 09:22 UTC, frenchykiller approved these changes

2021-05-26 09:23 UTC, merged