Implemented the subject list page
Lern-PFR/lern-web pull request #33
Opened 2021-06-08 17:58 UTC by simonfranza

2021-06-13 15:00 UTC, frenchykiller requested changes

2021-06-13 15:00 UTC, frenchykiller commented on src/i18n/en.json
> +				"no_data": "No subject found with the specified criterias."
criteria is uncountable (no s)

2021-06-13 15:00 UTC, frenchykiller commented on src/i18n/en.json
> +					"no_data": "This subject doesn't have any module, yet."
modules*

2021-06-13 15:00 UTC, frenchykiller commented on src/pages/subjects/SubjectListPage.jsx
> +		</StyledDiv>
All 3 sections contain the same list of subjects (every existing subject)

2021-06-13 15:00 UTC, frenchykiller commented on src/pages/subjects/SubjectDetailsPage.jsx
> +								{t('subjects.details.author_section', { author: subject?.author, lastUpdate: subject?.updatedAt })}
Displays correct author name when author is viewing their subject, displays no name when another user views the subject

2021-06-13 15:00 UTC, frenchykiller commented on src/pages/subjects/SubjectListPage.jsx
> +		setSearchValue(value);
Does not support searching by author

2021-06-14 19:11 UTC, simonfranza commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want a way to see all available subjects.](https://trello.com/c/iLjAl1ku/62-as-a-user-i-want-a-way-to-see-all-available-subjects)

2021-06-15 13:16 UTC, frenchykiller approved these changes

2021-06-15 15:21 UTC, merged