Implemented the subject creation page
Lern-PFR/lern-web pull request #36
Opened 2021-06-15 17:59 UTC by simonfranza

2021-06-15 17:59 UTC, simonfranza commented
![](https://github.trello.services/images/mini-trello-icon.png) [As an author, I want to have a subject creation page](https://trello.com/c/zkona1yb/76-as-an-author-i-want-to-have-a-subject-creation-page)

2021-06-15 19:28 UTC, frenchykiller requested changes

2021-06-15 19:28 UTC, frenchykiller commented on src/i18n/en.json
> +				"create": "Créer un nouveau sujet",
Create a new subject

2021-06-15 19:28 UTC, frenchykiller commented on src/pages/subjects/SubjectListPage.jsx
> +					<Link to={routes.subjects.subjectCreation}>{t('subjects.links.create')}</Link>
Move the button somewhere more visible (or have another button for the same action that is more visible): I spent 5 minutes looking and then had to get the url from the `routes.js` file

2021-06-16 10:30 UTC, frenchykiller approved these changes

2021-06-16 11:02 UTC, merged